import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  Upload: any;
};

/** Autogenerated input type of CreateProduct */
export type CreateProductInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  image: Scalars['Upload'];
  params: ProductInput;
};

/** Autogenerated return type of CreateProduct */
export type CreateProductPayload = {
  __typename?: 'CreateProductPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  product: Product;
};

export type Creator = {
  __typename?: 'Creator';
  /** クリエイターのカテゴリー */
  categories: Array<CreatorCategory>;
  /** クリエイターID */
  id: Scalars['ID'];
  /** クリエイター特有の情報 */
  info?: Maybe<CreatorInfo>;
  /** クリエイターの商品 */
  products?: Maybe<Array<Product>>;
  user: User;
};

export type CreatorCategory = {
  __typename?: 'CreatorCategory';
  creatorId: Scalars['ID'];
  /** クリエイターID */
  id: Scalars['ID'];
  /** カテゴリー */
  name: Scalars['String'];
};

export type CreatorInfo = {
  __typename?: 'CreatorInfo';
  /** 所属先 */
  belongs: Scalars['String'];
  creatorId: Scalars['ID'];
  /** クリエイターID */
  id: Scalars['ID'];
};

export type CreatorInput = {
  belongs: Scalars['String'];
  categoryId: Scalars['ID'];
};

/** Autogenerated input type of DeleteProductImage */
export type DeleteProductImageInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated return type of DeleteProductImage */
export type DeleteProductImagePayload = {
  __typename?: 'DeleteProductImagePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  product: Product;
};

/** Autogenerated input type of DeleteProduct */
export type DeleteProductInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated return type of DeleteProduct */
export type DeleteProductPayload = {
  __typename?: 'DeleteProductPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  product: Product;
};

/** Autogenerated input type of DeleteUserImage */
export type DeleteUserImageInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
};

/** Autogenerated return type of DeleteUserImage */
export type DeleteUserImagePayload = {
  __typename?: 'DeleteUserImagePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};

export enum GenderStatus {
  Male = 'male',
  Woman = 'woman'
}

export type Mutation = {
  __typename?: 'Mutation';
  createProduct?: Maybe<CreateProductPayload>;
  deleteProduct?: Maybe<DeleteProductPayload>;
  deleteProductImage?: Maybe<DeleteProductImagePayload>;
  deleteUserImage?: Maybe<DeleteUserImagePayload>;
  updateCreator?: Maybe<UpdateCreatorPayload>;
  updateProduct?: Maybe<UpdateProductPayload>;
  updateUser?: Maybe<UpdateUserPayload>;
  updateUserInfo?: Maybe<UpdateUserInfoPayload>;
  uploadProductImage?: Maybe<UploadProductImagePayload>;
  uploadPurchaseVideo?: Maybe<UploadPurchaseVideoPayload>;
  uploadUserImage?: Maybe<UploadUserImagePayload>;
};


export type MutationCreateProductArgs = {
  input: CreateProductInput;
};


export type MutationDeleteProductArgs = {
  input: DeleteProductInput;
};


export type MutationDeleteProductImageArgs = {
  input: DeleteProductImageInput;
};


export type MutationDeleteUserImageArgs = {
  input: DeleteUserImageInput;
};


export type MutationUpdateCreatorArgs = {
  input: UpdateCreatorInput;
};


export type MutationUpdateProductArgs = {
  input: UpdateProductInput;
};


export type MutationUpdateUserArgs = {
  input: UpdateUserInput;
};


export type MutationUpdateUserInfoArgs = {
  input: UpdateUserInfoInput;
};


export type MutationUploadProductImageArgs = {
  input: UploadProductImageInput;
};


export type MutationUploadPurchaseVideoArgs = {
  input: UploadPurchaseVideoInput;
};


export type MutationUploadUserImageArgs = {
  input: UploadUserImageInput;
};

export type PaymentMethod = {
  __typename?: 'PaymentMethod';
  /** カードブランド */
  brand: Scalars['String'];
  expMonth: Scalars['Int'];
  expYear: Scalars['String'];
  /** payment_methodのid */
  id: Scalars['String'];
  last4: Scalars['String'];
};

export type Product = {
  __typename?: 'Product';
  description: Scalars['String'];
  /** プロダクトID */
  id: Scalars['ID'];
  image: ProductImage;
  name: Scalars['String'];
  price: Scalars['Int'];
  status: ProductStatus;
  stockQuantity: Scalars['Int'];
};

export type ProductImage = {
  __typename?: 'ProductImage';
  /** 画像のID */
  id: Scalars['ID'];
  /** 画像のURL */
  path: Scalars['String'];
};

export type ProductInput = {
  description: Scalars['String'];
  name: Scalars['String'];
  price: Scalars['Int'];
  stockQuantity: Scalars['Int'];
};

export enum ProductStatus {
  Active = 'active',
  Archived = 'archived',
  Draft = 'draft'
}

export type PurchaseVideo = {
  __typename?: 'PurchaseVideo';
  /** 動画のID */
  id: Scalars['ID'];
  /** 動画のURL */
  path: Scalars['String'];
};

export type Query = {
  __typename?: 'Query';
  allPurchases: Array<PurchaseVideo>;
  creator: Creator;
  creators: Array<Creator>;
  paymentMethods: Array<PaymentMethod>;
  product: Product;
  products: Array<Product>;
  purchase: PurchaseVideo;
  setupPaymentMethod: Stripe;
  user: User;
  users: Array<User>;
};


export type QueryCreatorArgs = {
  id?: InputMaybe<Scalars['ID']>;
};


export type QueryProductArgs = {
  id: Scalars['ID'];
};


export type QueryPurchaseArgs = {
  id: Scalars['ID'];
};


export type QueryUserArgs = {
  id?: InputMaybe<Scalars['ID']>;
};

export type Stripe = {
  __typename?: 'Stripe';
  /** クライアントに渡すkey */
  clientSecret: Scalars['String'];
};

/** Autogenerated input type of UpdateCreator */
export type UpdateCreatorInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  params: CreatorInput;
};

/** Autogenerated return type of UpdateCreator */
export type UpdateCreatorPayload = {
  __typename?: 'UpdateCreatorPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  creator: Creator;
};

/** Autogenerated input type of UpdateProduct */
export type UpdateProductInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
  params: ProductInput;
};

/** Autogenerated return type of UpdateProduct */
export type UpdateProductPayload = {
  __typename?: 'UpdateProductPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  product: Product;
};

/** Autogenerated input type of UpdateUserInfo */
export type UpdateUserInfoInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  params?: InputMaybe<UserInfoInput>;
};

/** Autogenerated return type of UpdateUserInfo */
export type UpdateUserInfoPayload = {
  __typename?: 'UpdateUserInfoPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};

/** Autogenerated input type of UpdateUser */
export type UpdateUserInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  params: UserInput;
};

/** Autogenerated return type of UpdateUser */
export type UpdateUserPayload = {
  __typename?: 'UpdateUserPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};

/** Autogenerated input type of UploadProductImage */
export type UploadProductImageInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
  image: Scalars['Upload'];
};

/** Autogenerated return type of UploadProductImage */
export type UploadProductImagePayload = {
  __typename?: 'UploadProductImagePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  product: Product;
};

/** Autogenerated input type of UploadPurchaseVideo */
export type UploadPurchaseVideoInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  userId: Scalars['ID'];
  video: Scalars['Upload'];
};

/** Autogenerated return type of UploadPurchaseVideo */
export type UploadPurchaseVideoPayload = {
  __typename?: 'UploadPurchaseVideoPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  purchaseVideo: PurchaseVideo;
};

/** Autogenerated input type of UploadUserImage */
export type UploadUserImageInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  image: Scalars['Upload'];
};

/** Autogenerated return type of UploadUserImage */
export type UploadUserImagePayload = {
  __typename?: 'UploadUserImagePayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};

export type User = {
  __typename?: 'User';
  /** 年齢 */
  age: Scalars['Int'];
  /** 誕生日 */
  birthDayDd: Scalars['Int'];
  /** 誕生月 */
  birthDayMm: Scalars['Int'];
  /** 誕生年 */
  birthDayYy: Scalars['Int'];
  gender: GenderStatus;
  id: Scalars['ID'];
  images: Array<UserImage>;
  info?: Maybe<UserInfo>;
  instagramLink: Scalars['String'];
  introduction: Scalars['String'];
  name: Scalars['String'];
  /** @** のようなuserの識別子 */
  slug: Scalars['String'];
  tiktokLink: Scalars['String'];
  twitterLink: Scalars['String'];
};

export type UserImage = {
  __typename?: 'UserImage';
  /** 画像のID */
  id: Scalars['ID'];
  /** 画像のURL */
  path: Scalars['String'];
};

export type UserInfo = {
  __typename?: 'UserInfo';
  /** クリエイターID */
  id: Scalars['ID'];
  /** 推し */
  stan: Scalars['String'];
  userId: Scalars['ID'];
};

export type UserInfoInput = {
  stan?: InputMaybe<Scalars['String']>;
};

export type UserInput = {
  birthDayDd: Scalars['Int'];
  birthDayMm: Scalars['Int'];
  birthDayYy: Scalars['Int'];
  gender: GenderStatus;
  instagramLink?: InputMaybe<Scalars['String']>;
  introduction?: InputMaybe<Scalars['String']>;
  name: Scalars['String'];
  tiktokLink?: InputMaybe<Scalars['String']>;
  twitterLink?: InputMaybe<Scalars['String']>;
};

export type DeleteUserImageMutationVariables = Exact<{
  input: DeleteUserImageInput;
}>;


export type DeleteUserImageMutation = { __typename?: 'Mutation', deleteUserImage?: { __typename?: 'DeleteUserImagePayload', user: { __typename?: 'User', id: string, slug: string, name: string, introduction: string, gender: GenderStatus, age: number, birthDayYy: number, birthDayMm: number, birthDayDd: number, twitterLink: string, instagramLink: string, tiktokLink: string, images: Array<{ __typename?: 'UserImage', id: string, path: string }>, info?: { __typename?: 'UserInfo', id: string, stan: string, userId: string } | null } } | null };

export type UpdateUserMutationVariables = Exact<{
  input: UpdateUserInput;
}>;


export type UpdateUserMutation = { __typename?: 'Mutation', updateUser?: { __typename?: 'UpdateUserPayload', user: { __typename?: 'User', id: string, slug: string, name: string, introduction: string, gender: GenderStatus, age: number, birthDayYy: number, birthDayMm: number, birthDayDd: number, twitterLink: string, instagramLink: string, tiktokLink: string, images: Array<{ __typename?: 'UserImage', id: string, path: string }> } } | null };

export type UploadUserImageMutationVariables = Exact<{
  input: UploadUserImageInput;
}>;


export type UploadUserImageMutation = { __typename?: 'Mutation', uploadUserImage?: { __typename?: 'UploadUserImagePayload', user: { __typename?: 'User', id: string, slug: string, name: string, introduction: string, gender: GenderStatus, age: number, birthDayYy: number, birthDayMm: number, birthDayDd: number, twitterLink: string, instagramLink: string, tiktokLink: string, images: Array<{ __typename?: 'UserImage', id: string, path: string }>, info?: { __typename?: 'UserInfo', id: string, stan: string, userId: string } | null } } | null };

export type CreatorQueryVariables = Exact<{
  input: Scalars['ID'];
}>;


export type CreatorQuery = { __typename?: 'Query', creator: { __typename?: 'Creator', id: string, user: { __typename?: 'User', id: string, slug: string, name: string, introduction: string, gender: GenderStatus, age: number, birthDayYy: number, birthDayMm: number, birthDayDd: number, twitterLink: string, instagramLink: string, tiktokLink: string, images: Array<{ __typename?: 'UserImage', id: string, path: string }> }, info?: { __typename?: 'CreatorInfo', belongs: string } | null, categories: Array<{ __typename?: 'CreatorCategory', id: string, name: string }>, products?: Array<{ __typename?: 'Product', id: string, name: string, status: ProductStatus, price: number, image: { __typename?: 'ProductImage', id: string, path: string } }> | null } };

export type CreatorsQueryVariables = Exact<{ [key: string]: never; }>;


export type CreatorsQuery = { __typename?: 'Query', creators: Array<{ __typename?: 'Creator', id: string, user: { __typename?: 'User', slug: string, name: string, gender: GenderStatus, images: Array<{ __typename?: 'UserImage', id: string, path: string }> }, categories: Array<{ __typename?: 'CreatorCategory', name: string }> }> };

export type CurrentUserQueryVariables = Exact<{ [key: string]: never; }>;


export type CurrentUserQuery = { __typename?: 'Query', user: { __typename?: 'User', id: string, slug: string, name: string, introduction: string, gender: GenderStatus, age: number, birthDayYy: number, birthDayMm: number, birthDayDd: number, twitterLink: string, instagramLink: string, tiktokLink: string, images: Array<{ __typename?: 'UserImage', id: string, path: string }>, info?: { __typename?: 'UserInfo', id: string, stan: string, userId: string } | null } };

export type PaymentMethodsQueryVariables = Exact<{ [key: string]: never; }>;


export type PaymentMethodsQuery = { __typename?: 'Query', paymentMethods: Array<{ __typename?: 'PaymentMethod', id: string, brand: string, expMonth: number, expYear: string }> };

export type ProductQueryVariables = Exact<{
  input: Scalars['ID'];
}>;


export type ProductQuery = { __typename?: 'Query', product: { __typename?: 'Product', id: string, name: string, description: string, price: number, status: ProductStatus, stockQuantity: number, image: { __typename?: 'ProductImage', id: string, path: string } } };

export type ProductsIdQueryVariables = Exact<{ [key: string]: never; }>;


export type ProductsIdQuery = { __typename?: 'Query', products: Array<{ __typename?: 'Product', id: string }> };

export type SetupPaymentMethodQueryVariables = Exact<{ [key: string]: never; }>;


export type SetupPaymentMethodQuery = { __typename?: 'Query', setupPaymentMethod: { __typename?: 'Stripe', clientSecret: string } };

export type UserQueryVariables = Exact<{
  input: Scalars['ID'];
}>;


export type UserQuery = { __typename?: 'Query', user: { __typename?: 'User', id: string, slug: string, name: string, introduction: string, gender: GenderStatus, age: number, birthDayYy: number, birthDayMm: number, birthDayDd: number, twitterLink: string, instagramLink: string, tiktokLink: string, images: Array<{ __typename?: 'UserImage', id: string, path: string }>, info?: { __typename?: 'UserInfo', id: string, stan: string, userId: string } | null } };

export type UsersIdSlugQueryVariables = Exact<{ [key: string]: never; }>;


export type UsersIdSlugQuery = { __typename?: 'Query', users: Array<{ __typename?: 'User', id: string, slug: string }> };


export const DeleteUserImageDocument = gql`
    mutation DeleteUserImage($input: DeleteUserImageInput!) {
  deleteUserImage(input: $input) {
    user {
      id
      slug
      name
      introduction
      gender
      age
      birthDayYy
      birthDayMm
      birthDayDd
      twitterLink
      instagramLink
      tiktokLink
      images {
        id
        path
      }
      info {
        id
        stan
        userId
      }
    }
  }
}
    `;
export type DeleteUserImageMutationFn = Apollo.MutationFunction<DeleteUserImageMutation, DeleteUserImageMutationVariables>;

/**
 * __useDeleteUserImageMutation__
 *
 * To run a mutation, you first call `useDeleteUserImageMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useDeleteUserImageMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [deleteUserImageMutation, { data, loading, error }] = useDeleteUserImageMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useDeleteUserImageMutation(baseOptions?: Apollo.MutationHookOptions<DeleteUserImageMutation, DeleteUserImageMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<DeleteUserImageMutation, DeleteUserImageMutationVariables>(DeleteUserImageDocument, options);
      }
export type DeleteUserImageMutationHookResult = ReturnType<typeof useDeleteUserImageMutation>;
export type DeleteUserImageMutationResult = Apollo.MutationResult<DeleteUserImageMutation>;
export type DeleteUserImageMutationOptions = Apollo.BaseMutationOptions<DeleteUserImageMutation, DeleteUserImageMutationVariables>;
export const UpdateUserDocument = gql`
    mutation UpdateUser($input: UpdateUserInput!) {
  updateUser(input: $input) {
    user {
      id
      slug
      name
      introduction
      gender
      age
      birthDayYy
      birthDayMm
      birthDayDd
      twitterLink
      instagramLink
      tiktokLink
      images {
        id
        path
      }
    }
  }
}
    `;
export type UpdateUserMutationFn = Apollo.MutationFunction<UpdateUserMutation, UpdateUserMutationVariables>;

/**
 * __useUpdateUserMutation__
 *
 * To run a mutation, you first call `useUpdateUserMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateUserMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateUserMutation, { data, loading, error }] = useUpdateUserMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useUpdateUserMutation(baseOptions?: Apollo.MutationHookOptions<UpdateUserMutation, UpdateUserMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UpdateUserMutation, UpdateUserMutationVariables>(UpdateUserDocument, options);
      }
export type UpdateUserMutationHookResult = ReturnType<typeof useUpdateUserMutation>;
export type UpdateUserMutationResult = Apollo.MutationResult<UpdateUserMutation>;
export type UpdateUserMutationOptions = Apollo.BaseMutationOptions<UpdateUserMutation, UpdateUserMutationVariables>;
export const UploadUserImageDocument = gql`
    mutation UploadUserImage($input: UploadUserImageInput!) {
  uploadUserImage(input: $input) {
    user {
      id
      slug
      name
      introduction
      gender
      age
      birthDayYy
      birthDayMm
      birthDayDd
      twitterLink
      instagramLink
      tiktokLink
      images {
        id
        path
      }
      info {
        id
        stan
        userId
      }
    }
  }
}
    `;
export type UploadUserImageMutationFn = Apollo.MutationFunction<UploadUserImageMutation, UploadUserImageMutationVariables>;

/**
 * __useUploadUserImageMutation__
 *
 * To run a mutation, you first call `useUploadUserImageMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUploadUserImageMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [uploadUserImageMutation, { data, loading, error }] = useUploadUserImageMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useUploadUserImageMutation(baseOptions?: Apollo.MutationHookOptions<UploadUserImageMutation, UploadUserImageMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UploadUserImageMutation, UploadUserImageMutationVariables>(UploadUserImageDocument, options);
      }
export type UploadUserImageMutationHookResult = ReturnType<typeof useUploadUserImageMutation>;
export type UploadUserImageMutationResult = Apollo.MutationResult<UploadUserImageMutation>;
export type UploadUserImageMutationOptions = Apollo.BaseMutationOptions<UploadUserImageMutation, UploadUserImageMutationVariables>;
export const CreatorDocument = gql`
    query Creator($input: ID!) {
  creator(id: $input) {
    id
    user {
      id
      slug
      name
      introduction
      gender
      age
      birthDayYy
      birthDayMm
      birthDayDd
      twitterLink
      instagramLink
      tiktokLink
      images {
        id
        path
      }
    }
    info {
      belongs
    }
    categories {
      id
      name
    }
    products {
      id
      name
      status
      price
      image {
        id
        path
      }
    }
  }
}
    `;

/**
 * __useCreatorQuery__
 *
 * To run a query within a React component, call `useCreatorQuery` and pass it any options that fit your needs.
 * When your component renders, `useCreatorQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCreatorQuery({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useCreatorQuery(baseOptions: Apollo.QueryHookOptions<CreatorQuery, CreatorQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CreatorQuery, CreatorQueryVariables>(CreatorDocument, options);
      }
export function useCreatorLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CreatorQuery, CreatorQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CreatorQuery, CreatorQueryVariables>(CreatorDocument, options);
        }
export type CreatorQueryHookResult = ReturnType<typeof useCreatorQuery>;
export type CreatorLazyQueryHookResult = ReturnType<typeof useCreatorLazyQuery>;
export type CreatorQueryResult = Apollo.QueryResult<CreatorQuery, CreatorQueryVariables>;
export const CreatorsDocument = gql`
    query Creators {
  creators {
    id
    user {
      slug
      name
      gender
      images {
        id
        path
      }
    }
    categories {
      name
    }
  }
}
    `;

/**
 * __useCreatorsQuery__
 *
 * To run a query within a React component, call `useCreatorsQuery` and pass it any options that fit your needs.
 * When your component renders, `useCreatorsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCreatorsQuery({
 *   variables: {
 *   },
 * });
 */
export function useCreatorsQuery(baseOptions?: Apollo.QueryHookOptions<CreatorsQuery, CreatorsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CreatorsQuery, CreatorsQueryVariables>(CreatorsDocument, options);
      }
export function useCreatorsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CreatorsQuery, CreatorsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CreatorsQuery, CreatorsQueryVariables>(CreatorsDocument, options);
        }
export type CreatorsQueryHookResult = ReturnType<typeof useCreatorsQuery>;
export type CreatorsLazyQueryHookResult = ReturnType<typeof useCreatorsLazyQuery>;
export type CreatorsQueryResult = Apollo.QueryResult<CreatorsQuery, CreatorsQueryVariables>;
export const CurrentUserDocument = gql`
    query CurrentUser {
  user {
    id
    slug
    name
    introduction
    gender
    age
    birthDayYy
    birthDayMm
    birthDayDd
    twitterLink
    instagramLink
    tiktokLink
    images {
      id
      path
    }
    info {
      id
      stan
      userId
    }
  }
}
    `;

/**
 * __useCurrentUserQuery__
 *
 * To run a query within a React component, call `useCurrentUserQuery` and pass it any options that fit your needs.
 * When your component renders, `useCurrentUserQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCurrentUserQuery({
 *   variables: {
 *   },
 * });
 */
export function useCurrentUserQuery(baseOptions?: Apollo.QueryHookOptions<CurrentUserQuery, CurrentUserQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CurrentUserQuery, CurrentUserQueryVariables>(CurrentUserDocument, options);
      }
export function useCurrentUserLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CurrentUserQuery, CurrentUserQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CurrentUserQuery, CurrentUserQueryVariables>(CurrentUserDocument, options);
        }
export type CurrentUserQueryHookResult = ReturnType<typeof useCurrentUserQuery>;
export type CurrentUserLazyQueryHookResult = ReturnType<typeof useCurrentUserLazyQuery>;
export type CurrentUserQueryResult = Apollo.QueryResult<CurrentUserQuery, CurrentUserQueryVariables>;
export const PaymentMethodsDocument = gql`
    query PaymentMethods {
  paymentMethods {
    id
    brand
    expMonth
    expYear
  }
}
    `;

/**
 * __usePaymentMethodsQuery__
 *
 * To run a query within a React component, call `usePaymentMethodsQuery` and pass it any options that fit your needs.
 * When your component renders, `usePaymentMethodsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePaymentMethodsQuery({
 *   variables: {
 *   },
 * });
 */
export function usePaymentMethodsQuery(baseOptions?: Apollo.QueryHookOptions<PaymentMethodsQuery, PaymentMethodsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PaymentMethodsQuery, PaymentMethodsQueryVariables>(PaymentMethodsDocument, options);
      }
export function usePaymentMethodsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PaymentMethodsQuery, PaymentMethodsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PaymentMethodsQuery, PaymentMethodsQueryVariables>(PaymentMethodsDocument, options);
        }
export type PaymentMethodsQueryHookResult = ReturnType<typeof usePaymentMethodsQuery>;
export type PaymentMethodsLazyQueryHookResult = ReturnType<typeof usePaymentMethodsLazyQuery>;
export type PaymentMethodsQueryResult = Apollo.QueryResult<PaymentMethodsQuery, PaymentMethodsQueryVariables>;
export const ProductDocument = gql`
    query Product($input: ID!) {
  product(id: $input) {
    id
    name
    description
    price
    status
    stockQuantity
    image {
      id
      path
    }
  }
}
    `;

/**
 * __useProductQuery__
 *
 * To run a query within a React component, call `useProductQuery` and pass it any options that fit your needs.
 * When your component renders, `useProductQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useProductQuery({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useProductQuery(baseOptions: Apollo.QueryHookOptions<ProductQuery, ProductQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ProductQuery, ProductQueryVariables>(ProductDocument, options);
      }
export function useProductLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ProductQuery, ProductQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ProductQuery, ProductQueryVariables>(ProductDocument, options);
        }
export type ProductQueryHookResult = ReturnType<typeof useProductQuery>;
export type ProductLazyQueryHookResult = ReturnType<typeof useProductLazyQuery>;
export type ProductQueryResult = Apollo.QueryResult<ProductQuery, ProductQueryVariables>;
export const ProductsIdDocument = gql`
    query ProductsId {
  products {
    id
  }
}
    `;

/**
 * __useProductsIdQuery__
 *
 * To run a query within a React component, call `useProductsIdQuery` and pass it any options that fit your needs.
 * When your component renders, `useProductsIdQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useProductsIdQuery({
 *   variables: {
 *   },
 * });
 */
export function useProductsIdQuery(baseOptions?: Apollo.QueryHookOptions<ProductsIdQuery, ProductsIdQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<ProductsIdQuery, ProductsIdQueryVariables>(ProductsIdDocument, options);
      }
export function useProductsIdLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<ProductsIdQuery, ProductsIdQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<ProductsIdQuery, ProductsIdQueryVariables>(ProductsIdDocument, options);
        }
export type ProductsIdQueryHookResult = ReturnType<typeof useProductsIdQuery>;
export type ProductsIdLazyQueryHookResult = ReturnType<typeof useProductsIdLazyQuery>;
export type ProductsIdQueryResult = Apollo.QueryResult<ProductsIdQuery, ProductsIdQueryVariables>;
export const SetupPaymentMethodDocument = gql`
    query SetupPaymentMethod {
  setupPaymentMethod {
    clientSecret
  }
}
    `;

/**
 * __useSetupPaymentMethodQuery__
 *
 * To run a query within a React component, call `useSetupPaymentMethodQuery` and pass it any options that fit your needs.
 * When your component renders, `useSetupPaymentMethodQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useSetupPaymentMethodQuery({
 *   variables: {
 *   },
 * });
 */
export function useSetupPaymentMethodQuery(baseOptions?: Apollo.QueryHookOptions<SetupPaymentMethodQuery, SetupPaymentMethodQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<SetupPaymentMethodQuery, SetupPaymentMethodQueryVariables>(SetupPaymentMethodDocument, options);
      }
export function useSetupPaymentMethodLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<SetupPaymentMethodQuery, SetupPaymentMethodQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<SetupPaymentMethodQuery, SetupPaymentMethodQueryVariables>(SetupPaymentMethodDocument, options);
        }
export type SetupPaymentMethodQueryHookResult = ReturnType<typeof useSetupPaymentMethodQuery>;
export type SetupPaymentMethodLazyQueryHookResult = ReturnType<typeof useSetupPaymentMethodLazyQuery>;
export type SetupPaymentMethodQueryResult = Apollo.QueryResult<SetupPaymentMethodQuery, SetupPaymentMethodQueryVariables>;
export const UserDocument = gql`
    query User($input: ID!) {
  user(id: $input) {
    id
    slug
    name
    introduction
    gender
    age
    birthDayYy
    birthDayMm
    birthDayDd
    twitterLink
    instagramLink
    tiktokLink
    images {
      id
      path
    }
    info {
      id
      stan
      userId
    }
  }
}
    `;

/**
 * __useUserQuery__
 *
 * To run a query within a React component, call `useUserQuery` and pass it any options that fit your needs.
 * When your component renders, `useUserQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useUserQuery({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useUserQuery(baseOptions: Apollo.QueryHookOptions<UserQuery, UserQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<UserQuery, UserQueryVariables>(UserDocument, options);
      }
export function useUserLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<UserQuery, UserQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<UserQuery, UserQueryVariables>(UserDocument, options);
        }
export type UserQueryHookResult = ReturnType<typeof useUserQuery>;
export type UserLazyQueryHookResult = ReturnType<typeof useUserLazyQuery>;
export type UserQueryResult = Apollo.QueryResult<UserQuery, UserQueryVariables>;
export const UsersIdSlugDocument = gql`
    query UsersIdSlug {
  users {
    id
    slug
  }
}
    `;

/**
 * __useUsersIdSlugQuery__
 *
 * To run a query within a React component, call `useUsersIdSlugQuery` and pass it any options that fit your needs.
 * When your component renders, `useUsersIdSlugQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useUsersIdSlugQuery({
 *   variables: {
 *   },
 * });
 */
export function useUsersIdSlugQuery(baseOptions?: Apollo.QueryHookOptions<UsersIdSlugQuery, UsersIdSlugQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<UsersIdSlugQuery, UsersIdSlugQueryVariables>(UsersIdSlugDocument, options);
      }
export function useUsersIdSlugLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<UsersIdSlugQuery, UsersIdSlugQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<UsersIdSlugQuery, UsersIdSlugQueryVariables>(UsersIdSlugDocument, options);
        }
export type UsersIdSlugQueryHookResult = ReturnType<typeof useUsersIdSlugQuery>;
export type UsersIdSlugLazyQueryHookResult = ReturnType<typeof useUsersIdSlugLazyQuery>;
export type UsersIdSlugQueryResult = Apollo.QueryResult<UsersIdSlugQuery, UsersIdSlugQueryVariables>;