import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

/** Autogenerated input type of CreateUserDetail */
export type CreateUserDetailInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  params: UserDetailInput;
};

/** Autogenerated return type of CreateUserDetail */
export type CreateUserDetailPayload = {
  __typename?: 'CreateUserDetailPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};

export type Mutation = {
  __typename?: 'Mutation';
  createUserDetail?: Maybe<CreateUserDetailPayload>;
  updateUserDetail?: Maybe<UpdateUserDetailPayload>;
};


export type MutationCreateUserDetailArgs = {
  input: CreateUserDetailInput;
};


export type MutationUpdateUserDetailArgs = {
  input: UpdateUserDetailInput;
};

export type Query = {
  __typename?: 'Query';
  getUser: User;
  getUsers: Array<User>;
};


export type QueryGetUserArgs = {
  id?: InputMaybe<Scalars['ID']>;
};


export type QueryGetUsersArgs = {
  id?: InputMaybe<Scalars['ID']>;
};

/** Autogenerated input type of UpdateUserDetail */
export type UpdateUserDetailInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  id: Scalars['ID'];
  params: UserDetailInput;
};

/** Autogenerated return type of UpdateUserDetail */
export type UpdateUserDetailPayload = {
  __typename?: 'UpdateUserDetailPayload';
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  user: User;
};

export type User = {
  __typename?: 'User';
  birthDayDd?: Maybe<Scalars['Int']>;
  birthDayMm?: Maybe<Scalars['Int']>;
  birthDayYy?: Maybe<Scalars['Int']>;
  gender?: Maybe<Scalars['Int']>;
  id: Scalars['ID'];
  instagramLink?: Maybe<Scalars['String']>;
  introduction?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  tiktokLink?: Maybe<Scalars['String']>;
  twitterLink?: Maybe<Scalars['String']>;
  uid: Scalars['String'];
};

export type UserDetailInput = {
  birthDayDd?: InputMaybe<Scalars['Int']>;
  birthDayMm?: InputMaybe<Scalars['Int']>;
  birthDayYy?: InputMaybe<Scalars['Int']>;
  gender?: InputMaybe<Scalars['Int']>;
  instagramLink?: InputMaybe<Scalars['String']>;
  introduction?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  tiktokLink?: InputMaybe<Scalars['String']>;
  twitterLink?: InputMaybe<Scalars['String']>;
  uid?: InputMaybe<Scalars['String']>;
};

export type UserQueryVariables = Exact<{ [key: string]: never; }>;


export type UserQuery = { __typename?: 'Query', getUser: { __typename?: 'User', id: string } };


export const UserDocument = gql`
    query user {
  getUser {
    id
  }
}
    `;

/**
 * __useUserQuery__
 *
 * To run a query within a React component, call `useUserQuery` and pass it any options that fit your needs.
 * When your component renders, `useUserQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useUserQuery({
 *   variables: {
 *   },
 * });
 */
export function useUserQuery(baseOptions?: Apollo.QueryHookOptions<UserQuery, UserQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<UserQuery, UserQueryVariables>(UserDocument, options);
      }
export function useUserLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<UserQuery, UserQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<UserQuery, UserQueryVariables>(UserDocument, options);
        }
export type UserQueryHookResult = ReturnType<typeof useUserQuery>;
export type UserLazyQueryHookResult = ReturnType<typeof useUserLazyQuery>;
export type UserQueryResult = Apollo.QueryResult<UserQuery, UserQueryVariables>;